package com.example.myapplication.Model;

import android.content.Context;
import android.content.SharedPreferences;
import android.widget.Toast;

public class AlertManager {

    public static boolean checkLevels(Context context, double chlorine, double salt, double ph, double depth, double tds, double temperature) {

        SharedPreferences prefs = context.getSharedPreferences("AppPrefs", Context.MODE_PRIVATE);
        boolean alertEnabled = prefs.getBoolean("Alert", true);
        Toast.makeText(context, "New Alert", Toast.LENGTH_SHORT).show();

        boolean alertTriggered = false;

        // If user has not enabled Alert in settingsActivity, function is ignored
        if (!alertEnabled) return alertEnabled;

        // Condition to check before sending notifications. Values generated by chat and must be researched more before submission.
        if (chlorine < 1.0) {
            NotificationHelper.sendNotification(context,
                    "Low Chlorine",
                    "Add chlorine immediately.");
            alertTriggered = true;
        }

        if (salt < 2000) {
            NotificationHelper.sendNotification(context,
                    "Low Salt",
                    "Add salt to the pool.");
            alertTriggered = true;
        }

        if (ph < 7.2) {
            NotificationHelper.sendNotification(context,
                    "Low pH",
                    "Add pH increaser.");
            alertTriggered = true;
        } else if (ph > 7.8) {
            NotificationHelper.sendNotification(context,
                    "High pH",
                    "Add pH reducer.");
            alertTriggered = true;
        }

        if (depth < 30) {
            NotificationHelper.sendNotification(context,
                    "Low Water Level",
                    "Possibility of leakage");
            alertTriggered = true;
        }

        if (tds < 2000) {
            NotificationHelper.sendNotification(context,
                    "Bad Water Quality",
                    "Clean your pool");
            alertTriggered = true;
        }

        if (temperature < 15 ){
            NotificationHelper.sendNotification(context,
                    "Low Temperature",
                    "Turn on heater");
            alertTriggered = true;
        }

        return alertTriggered;
    }
}