package com.example.myapplication.Model;

import android.content.Context;
import android.content.SharedPreferences;

public class AlertManager {

    // This function is better in the backend instead.
    public static void checkLevels(Context context, double chlorine, double salt, double ph, int depth, int tds, double temperature) {

        SharedPreferences prefs = context.getSharedPreferences("AppPrefs", Context.MODE_PRIVATE);
        boolean alertEnabled = prefs.getBoolean("Alert", true);

        // If user has not enabled Alert in settingsActivity, function is ignored
        if (!alertEnabled) return;

        // Condition to check before sending notifications. Values generated by chat and must be researched more before submission.
        if (chlorine < 1.0) {
            NotificationHelper.sendNotification(context,
                    "Low Chlorine",
                    "Add chlorine immediately.");
        }

        if (salt < 2000) {
            NotificationHelper.sendNotification(context,
                    "Low Salt",
                    "Add salt to the pool.");
        }

        if (ph < 7.2) {
            NotificationHelper.sendNotification(context,
                    "Low pH",
                    "Add pH increaser.");
        } else if (ph > 7.8) {
            NotificationHelper.sendNotification(context,
                    "High pH",
                    "Add pH reducer.");
        }

        if (depth < 30) {
            NotificationHelper.sendNotification(context,
                    "Low Water Level",
                    "Possibility of leakage");
        }

        if (tds < 2000) {
            NotificationHelper.sendNotification(context,
                    "Bad Water Quality",
                    "Clean your pool");
        }

        if (temperature < 15 ){
            NotificationHelper.sendNotification(context,
                    "Low Temperature",
                    "Turn on heater");
        }

    }
}